Repository nss-evening-cohort-14/nautilus-explorer-dashboard-nautilus-explorer-dashboard, pull requests merged in 2021-03, with the labels that each got.

#38 Update README.md
  README.md
Labels: documentation

#40 Changed Issue Template
  ISSUE_TEMPLATE.md
Labels: documentation

#47 Hr development
  src/assets/captain.png
  src/assets/crew.png
  src/assets/crewOptionTwo.png
  src/assets/current.png
  src/assets/depth.png
  src/assets/destination.png
  src/assets/environmentalVariables.png
  src/assets/excursions.png
  src/assets/fullLogo.png
  src/assets/krakenIcon.png
  src/assets/log.png
  src/assets/logoOnly.png
  src/assets/pressure.png
  src/assets/temperature.png
  src/index.html
  src/javascripts/components/buttons/loginButton.js
  src/javascripts/components/buttons/logoutButton.js
  src/javascripts/components/domBuilder.js
  src/javascripts/components/loginButton.js
  src/javascripts/components/logoutButton.js
  src/javascripts/components/navBar.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/auth/apiKeys.js
  src/javascripts/helpers/auth/signIn.js
  src/javascripts/helpers/auth/signOut.js
  src/javascripts/helpers/router.js
  src/javascripts/main.js
  src/javascripts/views/startApp.js
  src/styles/main.scss
Labels: enhancement

#53 polished code - standardized div containers across pages, fixed print…
  src/javascripts/components/domBuilder.js
  src/javascripts/components/forms/formModal.js
  src/javascripts/components/pages/crew.js
  src/javascripts/components/pages/destSpecies.js
  src/javascripts/components/pages/logEntry.js
  src/javascripts/components/pages/species.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/router.js
  src/javascripts/views/startApp.js
  src/styles/main.scss
Labels: bug

#54 Dashboard View
  src/javascripts/components/navBar.js
  src/javascripts/components/pages/dashboardView.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/views/startApp.js
  src/styles/main.scss
Labels: enhancement

#56 Made Destination View
  src/javascripts/components/pages/destinationsView.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/data/destinationsData.js
Labels: enhancement

#59 Fixed Button Bug
  src/javascripts/components/pages/crew.js
  src/javascripts/components/pages/logEntry.js
  src/javascripts/components/pages/species.js
  src/javascripts/views/startApp.js
Labels: bug

#57 Hr createspecies
  src/javascripts/components/forms/addSpecies.js
  src/javascripts/components/forms/selectDestination.js
  src/javascripts/components/pages/crew.js
  src/javascripts/components/pages/species.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/auth/signOut.js
  src/javascripts/helpers/data/crudSpecies.js
  src/styles/main.scss
Labels: enhancement

#60 Cm create logs
  src/javascripts/components/forms/addLogForm.js
  src/javascripts/components/forms/editLogForm.js
  src/javascripts/components/pages/logEntry.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/data/logEntryData.js
  src/styles/main.scss
Labels: enhancement

#61 CREATE Destinations
  src/javascripts/components/pages/destinationsView.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/data/destinationsData.js
  src/styles/main.scss
Labels: enhancement

#64 DELETE Destinations
  src/javascripts/components/pages/destinationsView.js
  src/javascripts/events/domEvents.js
  src/javascripts/helpers/data/destinationsData.js
  src/styles/main.scss
Labels: enhancement

#65 Cm delete logs
  src/javascripts/components/pages/destinationsView.js
  src/javascripts/components/pages/logEntry.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/data/destinationsData.js
  src/javascripts/helpers/data/logEntryData.js
  src/styles/main.scss
Labels: enhancement

#66 Hr cru d species
  src/javascripts/components/pages/species.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/data/crudSpecies.js
Labels: enhancement

#68 Update Destinations
  src/index.html
  src/javascripts/components/forms/updateDestinationForm.js
  src/javascripts/components/pages/destinationsView.js
  src/javascripts/events/domEvents.js
  src/javascripts/helpers/data/destinationsData.js
  src/styles/main.scss
Labels: enhancement

#70 Cr ud species
  src/javascripts/components/forms/editSpecies.js
  src/javascripts/components/pages/dashboardView.js
  src/javascripts/components/pages/logEntry.js
  src/javascripts/components/pages/species.js
  src/javascripts/events/domEvents.js
  src/javascripts/helpers/data/crudSpecies.js
  src/styles/main.scss
Labels: enhancement

#74 Destination species
  src/javascripts/components/forms/addSpecies.js
  src/javascripts/components/forms/editSpecies.js
  src/javascripts/components/forms/selectDestination.js
  src/javascripts/components/pages/species.js
  src/javascripts/events/domEvents.js
  src/javascripts/helpers/data/destSpeciesData.js
  src/javascripts/helpers/data/destinationsData.js
Labels: enhancement

#76 bug fix
  src/javascripts/components/pages/species.js
  src/javascripts/events/domEvents.js
Labels: bug

#79 Fixed Duplicate CREATE's After Logging In
  src/javascripts/events/domEvents.js
  src/javascripts/views/startApp.js
Labels: bug

#81 Stretch
  src/javascripts/components/forms/addEnv.js
  src/javascripts/components/forms/addExcursion.js
  src/javascripts/components/forms/editExcursion.js
  src/javascripts/components/pages/dashboardView.js
  src/javascripts/components/pages/excursions.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/navigationEvents.js
  src/javascripts/helpers/auth/signOut.js
  src/javascripts/helpers/data/excursionCrud.js
  src/styles/main.scss
Labels: enhancement

#82 Hr create env
  src/javascripts/components/forms/addEnvironmental.js
  src/javascripts/components/pages/environmental.js
  src/javascripts/events/domEvents.js
  src/javascripts/helpers/data/environmentalData.js
  src/styles/main.scss
Labels: enhancement
